### PR TITLE
odbc_result/connection: better reference accounting

### LINKED ISSUE #716: odbc segfaults when executing multiple queries since commit 5b36b47
### Issue Description and Expected Result
Multiple `dbGetQuery` calls leads to segfault on macOS. I used `git bisect` and found the problem was introduced in commit 5b36b47.

### Database

SQL Server 2016

### Reproducible Example
```r
library(odbc)
con = dbConnect(odbc(), "MT_SI_AppSupport", uid = Sys.getenv('ODBC_UID'), pwd = Sys.getenv('ODBC_PWD'))
dbGetQuery(con, "SELECT TOP 2 * FROM abc_peak_occupancy")
dbGetQuery(con, "SELECT TOP 2 * FROM covid_apc")

 *** caught segfault ***
address 0x0, cause 'invalid permissions'

Traceback:
 1: new_result(p = connection@ptr, sql = statement, immediate = immediate)
 2: OdbcResult(connection = conn, statement = statement, params = params,     immediate = immediate)
 3: .local(conn, statement, ...)
 4: dbSendQuery(conn, statement, params = params, immediate = immediate,     ...)
 5: dbSendQuery(conn, statement, params = params, immediate = immediate,     ...)
 6: .local(conn, statement, ...)
 7: dbGetQuery(apps, "SELECT TOP 2 * FROM covid_apc")
 8: dbGetQuery(apps, "SELECT TOP 2 * FROM covid_apc")

```

Disconnecting after running a simple query will result in the following warning:

```r
library(odbc)
con = dbConnect(odbc(), "MT_SI_AppSupport", uid = Sys.getenv('ODBC_UID'), pwd = Sys.getenv('ODBC_PWD'))
dbGetQuery(con, "SELECT TOP 2 * FROM abc_peak_occupancy")
dbDisconnect(con)

Warning message:
In connection_release(conn@ptr) : There is a result object still in use.
The connection will be automatically released when it is closed
```

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> ─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.2 (2023-10-31)
 os       macOS Sonoma 14.2.1
 system   aarch64, darwin20
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Chicago
 date     2024-01-02
 pandoc   3.1.11 @ /opt/homebrew/bin/pandoc

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 bit           4.0.5   2022-11-15 [1] CRAN (R 4.3.0)
 bit64         4.0.5   2020-08-30 [1] CRAN (R 4.3.0)
 blob          1.2.4   2023-03-17 [1] CRAN (R 4.3.0)
 cachem        1.0.8   2023-05-01 [1] CRAN (R 4.3.0)
 cli           3.6.2   2023-12-11 [1] CRAN (R 4.3.1)
 DBI           1.2.0   2023-12-21 [1] CRAN (R 4.3.2)
 devtools      2.4.5   2022-10-11 [1] CRAN (R 4.3.0)
 digest        0.6.33  2023-07-07 [1] CRAN (R 4.3.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.3.0)
 fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.3.0)
 fs            1.6.3   2023-07-20 [1] CRAN (R 4.3.0)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.3.0)
 hms           1.1.3   2023-03-21 [1] CRAN (R 4.3.0)
 htmltools     0.5.7   2023-11-03 [1] CRAN (R 4.3.1)
 htmlwidgets   1.6.4   2023-12-06 [1] CRAN (R 4.3.1)
 httpuv        1.6.13  2023-12-06 [1] CRAN (R 4.3.1)
 later         1.3.2   2023-12-06 [1] CRAN (R 4.3.1)
 lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.3.1)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.3.0)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.3.0)
 mime          0.12    2021-09-28 [1] CRAN (R 4.3.0)
 miniUI        0.1.1.1 2018-05-18 [1] CRAN (R 4.3.0)
 nvimcom     * 0.9-157 2023-12-01 [1] local
 odbc        * 1.4.1   2023-12-21 [1] CRAN (R 4.3.1)
 pkgbuild      1.4.3   2023-12-10 [1] CRAN (R 4.3.1)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.3.0)
 pkgload       1.3.3   2023-09-22 [1] CRAN (R 4.3.1)
 profvis       0.3.8   2023-05-02 [1] CRAN (R 4.3.0)
 promises      1.2.1   2023-08-10 [1] CRAN (R 4.3.0)
 purrr         1.0.2   2023-08-10 [1] CRAN (R 4.3.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.3.0)
 Rcpp          1.0.11  2023-07-06 [1] CRAN (R 4.3.0)
 remotes       2.4.2.1 2023-07-18 [1] CRAN (R 4.3.0)
 rlang         1.1.2   2023-11-04 [1] CRAN (R 4.3.1)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.3.0)
 shiny         1.8.0   2023-11-17 [1] CRAN (R 4.3.1)
 stringi       1.8.3   2023-12-11 [1] CRAN (R 4.3.1)
 stringr       1.5.1   2023-11-14 [1] CRAN (R 4.3.1)
 urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.3.0)
 usethis       2.2.2   2023-07-06 [1] CRAN (R 4.3.0)
 vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.3.1)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.3.0)

 [1] /Users/***/Library/R/arm64/4.3/library
 [2] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```
</details>

### PR DESCRIPTION
**Pull request by detule**
Fixes #716

### CODE REVIEW

File: src/odbc_result.cpp [hunk 1]
```diff
@@ -214,6 +214,12 @@ odbc_result::~odbc_result() {
     try {
       c_->set_current_result(nullptr);
     } catch (...) {
+      // SQLCancel may throw an error.
```
Comment (hadley) [inline src/odbc_result.cpp:217]: Are you sure this code shouldn't belong in `odbc_connection::cancel_current_result()`?

Re-looking at this code also made me realise that the `warning()` is potentially dangerous because if `options(warn = 2)` is set, then we'll never get to the `cancel()`. We should probably add a test for that case too, using something like `withr::local_options(warn = 2)`.

File: NEWS.md [hunk 2]
```diff
@@ -1,5 +1,8 @@
 # odbc (development version)
 
+* freetds: Fix regression when executing multiple queries
+  (@detule, #731)
```
Comment (simonpcouch) [inline NEWS.md:4]:
```suggestion
  (@detule, #731).
```

**Review by simonpcouch — APPROVED** [review]
I only have as much intuition on the C++ changes as ChatGPT could give me, but I can confirm that I don't see the segfault from the linked issue with these changes. :)

File: src/odbc_result.cpp (hunk 1 above)
Comment (detule) [reply src/odbc_result.cpp:217]: Hey Hadley - thanks for taking a look.

I think this is a good spot for it.  We could try/catch closer to the place that throws currently.  But I think we still need to update the exception handling here in case another piece of code throws ( now, or in the future, if we were to expand set_current_result / etc ).

Comment (hadley) [reply src/odbc_result.cpp:217]: It feels weird to me because the job of `c_->set_current_result(nullptr)` is to reset the current result, and now its purpose is leaking out side of its scope. i.e. I think it's a code smell that you have to use friend here in order to reach inside the implementation detail of another function.

Comment (detule) [reply src/odbc_result.cpp:217]: Hi Hadley - thank you for continuing to think about this.

I think using `friend` here is OK:  the `odbc_connection/odbc_result` relationship is more than a bit incestuous to begin with, with both holding a (private) reference to each other.  Looks like we needed to forward declare the objects just to get the code to compile.

In terms of leaking purpose: `set_current_result` has two jobs - cancel the current statement with some caseology sprinkled in ( `throw`s ) and second, reset the pointer.  As we can't `throw` in the destructor, we could try and separate the calls - for example, wrap that second role in a oneliner `public void reset_result_ptr( odbc_result* r ) noexcept` method.  This would make it also so that we do not need to make the  classes `friend`s.   But I think I would probably still call that method in the destructor over adding exception handling in `set_current_result`.  The destructor might look something like this:

```
try {
        c_->cancel_current_result(true);
} catch (...) {
};
c_->reset_result_ptr(nullptr);
```

Anyway - not really tied to anything here.  Happy to go in a different direction.

Comment (hadley) [reply src/odbc_result.cpp:217]: I was thinking about this being a destructor last night — I think that means we can't call `Rcpp::warning()` safely at all here, because it might long jump, and while I can't remember exactly what happens when you long jump out of C++ destructor I know it's not good. 

How about we merge this PR to fix the pressing problem and then file another issue to rethink the design of this system to be safer?

Comment (detule) [reply src/odbc_result.cpp:217]: Sounds good - thanks!
