### PR TITLE
address bug in spark configuration helper

### LINKED ISSUE #835: "object 'unixodbc_install' not found" error in databricks connection
#825 introduced an issue with `configure_spark()` (only called in `databricks()`):

``` r
library(odbc)

dbConnect(databricks())
#> Error in h(simpleError(msg, call)): error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': object 'unixodbc_install' not found
```

<sup>Created on 2024-08-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

The bug is still only in dev odbc, i.e. hasn't made it to CRAN yet.

### PR DESCRIPTION
**Pull request by simonpcouch**
Closes #835.

EDIT: No NEWS entry as these changes hadn't yet made it to CRAN.

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -253,7 +253,8 @@ configure_spark <- function(call = caller_env()) {
     return(invisible())
   }
 
-  if (length(locate_install_unixodbc()) == 0) {
+  unixodbc_install <- locate_install_unixodbc()
+  if (length(unixodbc_install) == 0) {
     error_install_unixodbc(call)
   }
```
Comment (simonpcouch) [inline R/utils.R:260]: "Expand down" here will reveal the issue—`unixodbc_install` had been erroneously refactored out.

**Review by hadley — APPROVED** [review]
