### PR TITLE
API refactor + Oracle fixes

### LINKED ISSUE #575: Oracle: odbcConnectionColumns no-op
```r
> odbcConnectionColumns(conn, DBI::Id(schema="SA", table="TEST_TABLE"))
Error in connection_sql_columns(conn@ptr, table_name = name, catalog_name = catalog_name,  :
   nanodbc/nanodbc.cpp:2809: 00000: [Oracle][ODBC]Invalid SQL data type <-25>.
```

### PR DESCRIPTION
**Pull request by detule**
Hi:

Fixes #575 , #540, #554

Some highlights:
- Previously we had runaway usage of `connection_sql_tables`, which accommodates "magic" parameter ( combinations ).  This makes it difficult to customize parts of its functionality for individual back-ends.  Now some of the magic use cases are split out into `odbcConnectionCatalogs`, `odbcConnectionSchemas`, and `odbcConnectionTableTypes`.

- Specialize some of these for Oracle so that (hopefully) all of these are more performant ( and functional ): listing tables, writing to tables, and Rstudio/Viewer operations.

### CODE REVIEW

File: R/Viewer.R [hunk 1]
```diff
@@ -84,7 +84,8 @@ odbcListObjects.OdbcConnection <- function(connection, catalog = NULL, schema =
   # if no catalog was supplied but this database has catalogs, return a list of
   # catalogs
   if (is.null(catalog)) {
-    catalogs <- string_values(connection_sql_tables(connection@ptr, catalog_name = "%", "", "", NULL)[["table_catalog"]])
+    catalogs <- tryCatch(
+      string_values(odbcConnectionCatalogs(connection)), error = function(e) vector(mode = "character"))
```
Comment (hadley) [inline R/Viewer.R:88]:
```suggestion
    catalogs <- tryCatch(
      string_values(odbcConnectionCatalogs(connection)), 
      error = function(err) character()
    )
```

File: R/Viewer.R [hunk 2]
```diff
@@ -346,12 +347,12 @@ odbcConnectionActions.default <- function(connection) {
               tableName <- dbQuoteIdentifier(connection, firstTable$table_name)
 
               # add schema
-              if (!is.null(firstTable$table_schema) && nchar(firstTable$table_schema) > 0) {
+              if (!is.null(firstTable$table_schema) && !is.na(firstTable$table_schema) && nchar(firstTable$table_schema) > 0) {
```
Comment (hadley) [inline R/Viewer.R:350]: This level of type flexibility always makes me a bit nervous. Could we add some type checks higher up so we only need to check for one empty sentinel?

File: R/db.R [hunk 3]
```diff
@@ -14,6 +14,76 @@ setMethod("sqlCreateTable", "Oracle",
...
+  "odbcConnectionTables",
+  c("Oracle", "character"),
+  function(conn, name, catalog_name = NULL, schema_name = NULL, table_type = NULL) {
+
+    qTable <- getSelector("object_name", name)
+    if (is.null(schema_name)) {
+      query <- paste0(" SELECT null AS \"table_catalog\", '", conn@info$username ,"' AS \"table_schema\", object_name AS \"table_name\", object_type AS \"table_type\", null AS \"table_remarks\"",
+                      " FROM user_objects ",
+                      " WHERE 1 = 1 ", qTable,
+                      " AND ( object_type = 'TABLE' OR object_type = 'VIEW' ) ")
```
Comment (hadley) [inline R/db.R:33]:
```suggestion
      query <- paste0(
         " SELECT null AS \"table_catalog\", '", conn@info$username ,"' AS \"table_schema\", object_name AS \"table_name\", object_type AS \"table_type\", null AS \"table_remarks\"",
         " FROM user_objects ",
         " WHERE 1 = 1 ", qTable,
         " AND ( object_type = 'TABLE' OR object_type = 'VIEW' ) "
      )
```

etc

File: R/Connection.R [hunk 4]
```diff
@@ -191,6 +195,184 @@ setMethod(
...
+    connection_sql_tables(conn@ptr,
+      catalog_name = catalog_name,
+      schema_name = schema_name,
+      table_name = name,
+      table_type = table_type)
+
+  }
+)
+
+setMethod(
```
Comment (hadley) [inline R/Connection.R:271]: Missing `@rdname`?

File: R/Connection.R [hunk 5]
```diff
@@ -191,6 +195,184 @@ setMethod(
...
+#' @param conn OdbcConnection
+#' @param catalog_name Catalog where
+#' we are looking to list schemas.
+#' @rdname odbcConnectionSchemas
+setGeneric(
+  "odbcConnectionSchemas",
+  valueClass = "character",
+  function(conn, catalog_name) {
+    standardGeneric("odbcConnectionSchemas")
+  }
```
Comment (hadley) [inline R/Connection.R:332]:
```suggestion
  function(conn, catalog_name = NULL) {
    standardGeneric("odbcConnectionSchemas")
  }
```

Does that allow you to avoid the new `missingOrNULL` class union?

**Review by hadley — APPROVED** [review]

File: R/db.R (hunk 3 above)
Comment (detule) [reply R/db.R]: Done - thanks!

File: R/Connection.R (hunk 5 above)
Comment (detule) [reply R/Connection.R:331]: Good idea - done / thanks!

File: R/Viewer.R (hunk 2 above)
Comment (detule) [reply R/Viewer.R]: Thanks Hadley:

As best as I can tell, the `is.null(...)` that was there to begin-with is not guarding anything; I think only the `is.na` is actually effective.

Kind of hesitant to remove the `is.null` since I am not sure why it was there in the first place.  But at the same time this is not in any critical code-path; we can revisit if remove it breaks something.
